language: java
jdk:
- oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
- provider: heroku
  api_key:
    secure: RqRzCps3iYwLwpVgxOp95dInggT8k7zMw5+d53QO+s+zfmSkwWH4wSvwTe6gy30jNPU6MJFmR6RmXjJsQgR5stMP0CeAHWvM8EoeZJABbKALUbWx+Ajc9xWIoFP/BlYWY8zrY61udwoyCq32OWcFHc4QZeCjXZUUXie7fqYPaaisUZVzWZFqTiVoeQUPoNbPm5/U+udZ3Xyjv0ecwHze8YYYFJjcH1e8SkK5quAimV/P2Ws51jq+bLi/UoE6Nx09B4FjAdHtS9nntWR/VaM437kRR/0ebjtOazm9RYCubR398fZGkE85Qwfe/KqDUPTGdJVNsyv7j4nWR3exuHgY2yyWYrePorCk1T3TrGdDOfS9qIUl9Fw4SDLXFausnwqa/zRGKWVSN7u1OcrlgyJlZOOEiWU6ZIoEkUO0tWtTOinbpL3awsQ1/tjp2wE+PMnwPHBsOmatSZROYaetHVAR8PIqcdpOBqEvNj9oSNHmAihhr1uwLJ8fiPrw8WEPcXxZpE9mCqZXdilgUKbQKhkaL5YDZzlvxF60XiIz+76CeRYYE06vyhwkfi0aLIw5+SOUXHsqPVLI8vLdcjmaV203E2X46RSgDdwpT14W/vfjA8ZZ7tPtAFS86d1GkLjLSjFLnzcmxiOc/YrJBs+Ua/SsI8ST8S/dSoMhE4pLYqKats0=
  app:
    master: lit-eyrie-57326
    continuousIntegration: frozen-brushlands-27313
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - echo -e "machine api.heroku.com\n  login kristoferrt@gmail.com\n  password 8be33f5a-3f59-4612-90e9-b84eff7f7e69\nmachine git.heroku.com\n  login kristoferrt@gmail.com password 8be33f5a-3f59-4612-90e9-b84eff7f7e69" > ~/.netrc
  - chmod 0600 ~/.netrc
  - heroku --version
  - heroku git:remote -a powerrangers-tictactoe-staging # switch to staging app
  - git push heroku continuousIntegration:master        # push new site to heroku
  - ./gradlew selenium --stacktrace --info              # Run selenium tests
script:
  - heroku git:remote -a powerrangers-tictactoe   # Switch to production
  - git push heroku continuousIntegration:master  # Push to production
after_script:
  - heroku git:remote -a lit-eyrie-57326  # Switch back to staging
addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
