language: java
jdk:
- oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: heroku
  api_key:
    secure: RqRzCps3iYwLwpVgxOp95dInggT8k7zMw5+d53QO+s+zfmSkwWH4wSvwTe6gy30jNPU6MJFmR6RmXjJsQgR5stMP0CeAHWvM8EoeZJABbKALUbWx+Ajc9xWIoFP/BlYWY8zrY61udwoyCq32OWcFHc4QZeCjXZUUXie7fqYPaaisUZVzWZFqTiVoeQUPoNbPm5/U+udZ3Xyjv0ecwHze8YYYFJjcH1e8SkK5quAimV/P2Ws51jq+bLi/UoE6Nx09B4FjAdHtS9nntWR/VaM437kRR/0ebjtOazm9RYCubR398fZGkE85Qwfe/KqDUPTGdJVNsyv7j4nWR3exuHgY2yyWYrePorCk1T3TrGdDOfS9qIUl9Fw4SDLXFausnwqa/zRGKWVSN7u1OcrlgyJlZOOEiWU6ZIoEkUO0tWtTOinbpL3awsQ1/tjp2wE+PMnwPHBsOmatSZROYaetHVAR8PIqcdpOBqEvNj9oSNHmAihhr1uwLJ8fiPrw8WEPcXxZpE9mCqZXdilgUKbQKhkaL5YDZzlvxF60XiIz+76CeRYYE06vyhwkfi0aLIw5+SOUXHsqPVLI8vLdcjmaV203E2X46RSgDdwpT14W/vfjA8ZZ7tPtAFS86d1GkLjLSjFLnzcmxiOc/YrJBs+Ua/SsI8ST8S/dSoMhE4pLYqKats0=
  app:
    master: powerrangers-tictactoe
    SeleniumTests: powerrangers-tictactoe-staging
